In [104]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import mean_squared_error, mean_absolute_error, mean_absolute_percentage_error
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import accuracy_score, roc_auc_score, f1_score

In [56]:
data = pd.read_csv("Customer Churn.csv")

In [57]:
data

,Call Failure,Complains,Subscription Length,Charge Amount,Seconds of Use,Frequency of use,Frequency of SMS,Distinct Called Numbers,Age Group,Tariff Plan,Status,Age,Customer Value,Churn
0,8,0,38,0,4370,71,5,17,3,1,1,30,197.640,0
1,0,0,39,0,318,5,7,4,2,1,2,25,46.035,0
2,10,0,37,0,2453,60,359,24,3,1,1,30,1536.520,0
3,10,0,38,0,4198,66,1,35,1,1,1,15,240.020,0
4,3,0,38,0,2393,58,2,33,1,1,1,15,145.805,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3145,21,0,19,2,6697,147,92,44,2,2,1,25,721.980,0
3146,17,0,17,1,9237,177,80,42,5,1,1,55,261.210,0
3147,13,0,18,4,3157,51,38,21,3,1,1,30,280.320,0
3148,7,0,11,2,4695,46,222,12,3,1,1,30,1077.640,0
3149,8,1,11,2,1792,25,7,9,3,1,1,30,100.680,1

In [58]:
X = data.drop('Churn', axis=1)
Y = data['Churn']

In [59]:
X

,Call Failure,Complains,Subscription Length,Charge Amount,Seconds of Use,Frequency of use,Frequency of SMS,Distinct Called Numbers,Age Group,Tariff Plan,Status,Age,Customer Value
0,8,0,38,0,4370,71,5,17,3,1,1,30,197.640
1,0,0,39,0,318,5,7,4,2,1,2,25,46.035
2,10,0,37,0,2453,60,359,24,3,1,1,30,1536.520
3,10,0,38,0,4198,66,1,35,1,1,1,15,240.020
4,3,0,38,0,2393,58,2,33,1,1,1,15,145.805
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3145,21,0,19,2,6697,147,92,44,2,2,1,25,721.980
3146,17,0,17,1,9237,177,80,42,5,1,1,55,261.210
3147,13,0,18,4,3157,51,38,21,3,1,1,30,280.320
3148,7,0,11,2,4695,46,222,12,3,1,1,30,1077.640
3149,8,1,11,2,1792,25,7,9,3,1,1,30,100.680

In [60]:
Y

0       0
1       0
2       0
3       0
4       0
       ..
3145    0
3146    0
3147    0
3148    0
3149    1
Name: Churn, Length: 3150, dtype: int64

In [61]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

In [62]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [63]:
X_train_scaled_df = pd.DataFrame(X_train_scaled, columns=X_train.columns)
X_test_scaled_df = pd.DataFrame(X_test_scaled, columns=X_test.columns)

In [85]:
X_train_scaled_df

,Call Failure,Complains,Subscription Length,Charge Amount,Seconds of Use,Frequency of use,Frequency of SMS,Distinct Called Numbers,Age Group,Tariff Plan,Status,Age,Churn
0,-1.107299,-0.287248,-2.634015,-0.632816,-0.099463,-0.539115,1.236139,-0.687774,0.198856,-0.297267,-0.542559,-0.102633,-0.402807
1,0.417685,-0.287248,-1.704714,1.934608,-0.422517,-0.432834,-0.364389,-0.206566,0.198856,-0.297267,-0.542559,-0.102633,-0.402807
2,-1.107299,-0.287248,-1.588551,-0.632816,-0.743421,-0.787103,-0.399373,-0.447170,-0.930648,-0.297267,-0.542559,-0.674818,-0.402807
3,0.833590,3.481317,0.734703,-0.632816,-0.538406,-0.326554,-0.618024,-0.567472,0.198856,-0.297267,1.843118,-0.102633,-0.402807
4,-0.414125,-0.287248,0.734703,-0.632816,0.198740,0.311130,-0.679247,-0.627623,0.198856,-0.297267,-0.542559,-0.102633,-0.402807
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2409,-1.107299,-0.287248,0.037726,-0.632816,-0.748200,-0.592255,-0.329404,-0.206566,0.198856,-0.297267,1.843118,-0.102633,-0.402807
2410,0.279050,-0.287248,-2.053202,-0.632816,0.957391,1.692777,-0.058277,0.936301,1.328361,-0.297267,-0.542559,1.613923,-0.402807
2411,-1.107299,-0.287248,-0.078436,-0.632816,-0.317382,0.010001,-0.679247,-0.026114,-0.930648,-0.297267,-0.542559,-0.674818,-0.402807
2412,-0.968664,-0.287248,-0.310762,-0.632816,-0.351551,-0.113993,-0.591786,-0.266717,-0.930648,-0.297267,-0.542559,-0.674818,-0.402807
2413,1.942670,-0.287248,-1.704714,0.650896,0.578424,1.409362,0.134136,1.056603,-0.930648,3.363975,-0.542559,-0.674818,-0.402807

In [86]:
X_test_scaled_df

,Call Failure,Complains,Subscription Length,Charge Amount,Seconds of Use,Frequency of use,Frequency of SMS,Distinct Called Numbers,Age Group,Tariff Plan,Status,Age,Churn
0,-1.107299,-0.287248,-1.820877,-0.632816,-0.482971,-0.485974,-0.679247,-0.567472,0.198856,-0.297267,-0.542559,-0.102633,-0.402807
1,2.635845,-0.287248,0.386214,1.934608,2.722480,3.038997,-0.609278,3.402489,-0.930648,-0.297267,-0.542559,-0.674818,-0.402807
2,-0.136855,3.481317,-2.750178,1.292752,-0.619647,-0.769389,-0.495579,-0.146415,0.198856,-0.297267,-0.542559,-0.102633,2.482580
3,1.110860,-0.287248,-1.820877,0.009040,0.409012,1.214514,0.064168,1.056603,-0.930648,3.363975,-0.542559,-0.674818,-0.402807
4,-0.552760,-0.287248,-0.194599,1.292752,0.502679,0.629971,1.594727,0.214490,-0.930648,3.363975,-0.542559,-0.674818,-0.402807
...,...,...,...,...,...,...,...,...,...,...,...,...,...
599,-0.691395,-0.287248,0.618540,0.650896,-1.010323,-1.123658,-0.661754,-1.409585,2.457865,-0.297267,-0.542559,2.758294,-0.402807
600,-0.830029,-0.287248,0.153889,-0.632816,-0.565885,-0.291127,-0.679247,0.274641,-2.060152,-0.297267,-0.542559,-1.819189,-0.402807
601,0.972225,-0.287248,-0.194599,0.009040,-0.763731,-0.539115,-0.381881,-0.326868,-0.930648,-0.297267,-0.542559,-0.674818,-0.402807
602,0.279050,-0.287248,-1.123900,-0.632816,-0.970419,-0.875670,-0.679247,-1.289283,-0.930648,-0.297267,1.843118,-0.674818,-0.402807
603,0.417685,-0.287248,-2.285527,1.292752,-0.364215,-0.485974,-0.416865,-0.266717,0.198856,-0.297267,-0.542559,-0.102633,-0.402807

In [110]:
# this is the logistic regression model

In [64]:
lr = LogisticRegression(max_iter=5000, random_state=42)
lr.fit(X_train_scaled_df, Y_train)

LogisticRegression(max_iter=5000, random_state=42)

In [65]:
Y_pred_lr = lr.predict(X_test_scaled_df)
Y_prob_lr = lr.predict_proba(X_test_scaled_df)[:, 1]

In [66]:
print("Logistic Regression Performance:")
print("AUC:", roc_auc_score(Y_test, Y_prob_lr))
print("Accuracy:", accuracy_score(Y_test, Y_pred_lr))
print("F1 Score:", f1_score(Y_test, Y_pred_lr))

Logistic Regression Performance:
AUC: 0.9047115384615385
Accuracy: 0.8698412698412699
F1 Score: 0.5176470588235295

In [111]:
# this is thhe decision tree classifier model

In [67]:
dt = DecisionTreeClassifier(random_state=42)
dt.fit(X_train_scaled_df, Y_train)

DecisionTreeClassifier(random_state=42)

In [68]:
Y_pred_dt = dt.predict(X_test_scaled_df)
Y_prob_dt = dt.predict_proba(X_test_scaled_df)[:, 1]

In [69]:
print("\nDecision Tree Performance:")
print("AUC:", roc_auc_score(Y_test, Y_prob_dt))
print("Accuracy:", accuracy_score(Y_test, Y_pred_dt))
print("F1 Score:", f1_score(Y_test, Y_pred_dt))

Decision Tree Performance:
AUC: 0.9011975524475525
Accuracy: 0.9285714285714286
F1 Score: 0.7906976744186046

In [112]:
# this is the random forest classifier model

In [70]:
rf = RandomForestClassifier(random_state=42)
rf.fit(X_train_scaled_df, Y_train)

RandomForestClassifier(random_state=42)

In [71]:
Y_pred_rf = rf.predict(X_test_scaled_df)
Y_prob_rf = rf.predict_proba(X_test_scaled_df)[:, 1]

In [72]:
print("\nRandom Forest Performance:")
print("AUC:", roc_auc_score(Y_test, Y_prob_rf))
print("Accuracy:", accuracy_score(Y_test, Y_pred_rf))
print("F1 Score:", f1_score(Y_test, Y_pred_rf))

Random Forest Performance:
AUC: 0.9768356643356643
Accuracy: 0.9380952380952381
F1 Score: 0.8169014084507042

In [ ]:
### The random forest classifier model achieved the highest performance across all metrics, with an AUC of 0.977, an Accuracy of 0.938, and an F1 Score of 0.817.

In [113]:
##

In [108]:
# I will now do the regression task

In [87]:
data

,Call Failure,Complains,Subscription Length,Charge Amount,Seconds of Use,Frequency of use,Frequency of SMS,Distinct Called Numbers,Age Group,Tariff Plan,Status,Age,Customer Value,Churn
0,8,0,38,0,4370,71,5,17,3,1,1,30,197.640,0
1,0,0,39,0,318,5,7,4,2,1,2,25,46.035,0
2,10,0,37,0,2453,60,359,24,3,1,1,30,1536.520,0
3,10,0,38,0,4198,66,1,35,1,1,1,15,240.020,0
4,3,0,38,0,2393,58,2,33,1,1,1,15,145.805,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3145,21,0,19,2,6697,147,92,44,2,2,1,25,721.980,0
3146,17,0,17,1,9237,177,80,42,5,1,1,55,261.210,0
3147,13,0,18,4,3157,51,38,21,3,1,1,30,280.320,0
3148,7,0,11,2,4695,46,222,12,3,1,1,30,1077.640,0
3149,8,1,11,2,1792,25,7,9,3,1,1,30,100.680,1

In [74]:
data_reg = data[data['Customer Value'] != 0]

In [75]:
X = data_reg.drop(['Customer Value'], axis=1)
Y = data_reg['Customer Value']

In [76]:
X

,Call Failure,Complains,Subscription Length,Charge Amount,Seconds of Use,Frequency of use,Frequency of SMS,Distinct Called Numbers,Age Group,Tariff Plan,Status,Age,Churn
0,8,0,38,0,4370,71,5,17,3,1,1,30,0
1,0,0,39,0,318,5,7,4,2,1,2,25,0
2,10,0,37,0,2453,60,359,24,3,1,1,30,0
3,10,0,38,0,4198,66,1,35,1,1,1,15,0
4,3,0,38,0,2393,58,2,33,1,1,1,15,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3145,21,0,19,2,6697,147,92,44,2,2,1,25,0
3146,17,0,17,1,9237,177,80,42,5,1,1,55,0
3147,13,0,18,4,3157,51,38,21,3,1,1,30,0
3148,7,0,11,2,4695,46,222,12,3,1,1,30,0
3149,8,1,11,2,1792,25,7,9,3,1,1,30,1

In [77]:
Y

0        197.640
1         46.035
2       1536.520
3        240.020
4        145.805
          ...
3145     721.980
3146     261.210
3147     280.320
3148    1077.640
3149     100.680
Name: Customer Value, Length: 3018, dtype: float64

In [78]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

In [79]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [83]:
X_train_scaled

array([[-1.10729939, -0.28724765, -2.63401536, ..., -0.54255873,
        -0.10263308, -0.40280672],
       [ 0.41768521, -0.28724765, -1.70471388, ..., -0.54255873,
        -0.10263308, -0.40280672],
       [-1.10729939, -0.28724765, -1.58855119, ..., -0.54255873,
        -0.67481841, -0.40280672],
       ...,
       [-1.10729939, -0.28724765, -0.07843628, ..., -0.54255873,
        -0.67481841, -0.40280672],
       [-0.96866443, -0.28724765, -0.31076165, ..., -0.54255873,
        -0.67481841, -0.40280672],
       [ 1.94266981, -0.28724765, -1.70471388, ..., -0.54255873,
        -0.67481841, -0.40280672]])

In [84]:
X_test_scaled

array([[-1.10729939, -0.28724765, -1.82087656, ..., -0.54255873,
        -0.10263308, -0.40280672],
       [ 2.63584462, -0.28724765,  0.38621446, ..., -0.54255873,
        -0.67481841, -0.40280672],
       [-0.13685465,  3.48131659, -2.75017805, ..., -0.54255873,
        -0.10263308,  2.48258026],
       ...,
       [ 0.97222506, -0.28724765, -0.19459896, ..., -0.54255873,
        -0.67481841, -0.40280672],
       [ 0.27905024, -0.28724765, -1.12390045, ...,  1.84311845,
        -0.67481841, -0.40280672],
       [ 0.41768521, -0.28724765, -2.28552731, ..., -0.54255873,
        -0.10263308, -0.40280672]])

In [80]:
X_train_scaled_df = pd.DataFrame(X_train_scaled, columns=X_train.columns)
X_test_scaled_df = pd.DataFrame(X_test_scaled, columns=X_test.columns)

In [81]:
X_train_scaled_df

,Call Failure,Complains,Subscription Length,Charge Amount,Seconds of Use,Frequency of use,Frequency of SMS,Distinct Called Numbers,Age Group,Tariff Plan,Status,Age,Churn
0,-1.107299,-0.287248,-2.634015,-0.632816,-0.099463,-0.539115,1.236139,-0.687774,0.198856,-0.297267,-0.542559,-0.102633,-0.402807
1,0.417685,-0.287248,-1.704714,1.934608,-0.422517,-0.432834,-0.364389,-0.206566,0.198856,-0.297267,-0.542559,-0.102633,-0.402807
2,-1.107299,-0.287248,-1.588551,-0.632816,-0.743421,-0.787103,-0.399373,-0.447170,-0.930648,-0.297267,-0.542559,-0.674818,-0.402807
3,0.833590,3.481317,0.734703,-0.632816,-0.538406,-0.326554,-0.618024,-0.567472,0.198856,-0.297267,1.843118,-0.102633,-0.402807
4,-0.414125,-0.287248,0.734703,-0.632816,0.198740,0.311130,-0.679247,-0.627623,0.198856,-0.297267,-0.542559,-0.102633,-0.402807
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2409,-1.107299,-0.287248,0.037726,-0.632816,-0.748200,-0.592255,-0.329404,-0.206566,0.198856,-0.297267,1.843118,-0.102633,-0.402807
2410,0.279050,-0.287248,-2.053202,-0.632816,0.957391,1.692777,-0.058277,0.936301,1.328361,-0.297267,-0.542559,1.613923,-0.402807
2411,-1.107299,-0.287248,-0.078436,-0.632816,-0.317382,0.010001,-0.679247,-0.026114,-0.930648,-0.297267,-0.542559,-0.674818,-0.402807
2412,-0.968664,-0.287248,-0.310762,-0.632816,-0.351551,-0.113993,-0.591786,-0.266717,-0.930648,-0.297267,-0.542559,-0.674818,-0.402807
2413,1.942670,-0.287248,-1.704714,0.650896,0.578424,1.409362,0.134136,1.056603,-0.930648,3.363975,-0.542559,-0.674818,-0.402807

In [82]:
X_test_scaled_df

,Call Failure,Complains,Subscription Length,Charge Amount,Seconds of Use,Frequency of use,Frequency of SMS,Distinct Called Numbers,Age Group,Tariff Plan,Status,Age,Churn
0,-1.107299,-0.287248,-1.820877,-0.632816,-0.482971,-0.485974,-0.679247,-0.567472,0.198856,-0.297267,-0.542559,-0.102633,-0.402807
1,2.635845,-0.287248,0.386214,1.934608,2.722480,3.038997,-0.609278,3.402489,-0.930648,-0.297267,-0.542559,-0.674818,-0.402807
2,-0.136855,3.481317,-2.750178,1.292752,-0.619647,-0.769389,-0.495579,-0.146415,0.198856,-0.297267,-0.542559,-0.102633,2.482580
3,1.110860,-0.287248,-1.820877,0.009040,0.409012,1.214514,0.064168,1.056603,-0.930648,3.363975,-0.542559,-0.674818,-0.402807
4,-0.552760,-0.287248,-0.194599,1.292752,0.502679,0.629971,1.594727,0.214490,-0.930648,3.363975,-0.542559,-0.674818,-0.402807
...,...,...,...,...,...,...,...,...,...,...,...,...,...
599,-0.691395,-0.287248,0.618540,0.650896,-1.010323,-1.123658,-0.661754,-1.409585,2.457865,-0.297267,-0.542559,2.758294,-0.402807
600,-0.830029,-0.287248,0.153889,-0.632816,-0.565885,-0.291127,-0.679247,0.274641,-2.060152,-0.297267,-0.542559,-1.819189,-0.402807
601,0.972225,-0.287248,-0.194599,0.009040,-0.763731,-0.539115,-0.381881,-0.326868,-0.930648,-0.297267,-0.542559,-0.674818,-0.402807
602,0.279050,-0.287248,-1.123900,-0.632816,-0.970419,-0.875670,-0.679247,-1.289283,-0.930648,-0.297267,1.843118,-0.674818,-0.402807
603,0.417685,-0.287248,-2.285527,1.292752,-0.364215,-0.485974,-0.416865,-0.266717,0.198856,-0.297267,-0.542559,-0.102633,-0.402807

In [88]:
#the first model is a linear regression model

In [90]:
lr = LinearRegression()
lr.fit(X_train_scaled_df, Y_train)

LinearRegression()

In [92]:
Y_pred_lr = lr.predict(X_test_scaled_df)

In [93]:
print("Linear Regression Performance:")
print("RMSE:", np.sqrt(mean_squared_error(Y_test, Y_pred_lr)))
print("MAE:", mean_absolute_error(Y_test, Y_pred_lr))
print("MAPE:", mean_absolute_percentage_error(Y_test, Y_pred_lr))

Linear Regression Performance:
RMSE: 54.979069290153426
MAE: 37.09648351582239
MAPE: 0.5193095192375674

In [95]:
#the second model is a decision tree regressor

In [98]:
dt = DecisionTreeRegressor(random_state=42)
dt.fit(X_train_scaled_df, Y_train)

DecisionTreeRegressor(random_state=42)

In [99]:
Y_pred_dt = dt.predict(X_test_scaled_df)

In [100]:
print("\nDecision Tree Regressor Performance:")
print("RMSE:", np.sqrt(mean_squared_error(Y_test, Y_pred_dt)))
print("MAE:", mean_absolute_error(Y_test, Y_pred_dt))
print("MAPE:", mean_absolute_percentage_error(Y_test, Y_pred_dt))

Decision Tree Regressor Performance:
RMSE: 36.68963382052356
MAE: 15.029006622516556
MAPE: 0.06177063497095615

In [101]:
#the third model is a random forest regressor

In [105]:
rf = RandomForestRegressor(random_state=42)
rf.fit(X_train_scaled_df, Y_train)

RandomForestRegressor(random_state=42)

In [106]:
Y_pred_rf = rf.predict(X_test_scaled_df)

In [107]:
print("\nRandom Forest Regressor Performance:")
print("RMSE:", np.sqrt(mean_squared_error(Y_test, Y_pred_rf)))
print("MAE:", mean_absolute_error(Y_test, Y_pred_rf))
print("MAPE:", mean_absolute_percentage_error(Y_test, Y_pred_rf))

Random Forest Regressor Performance:
RMSE: 31.778489036894143
MAE: 11.028659023178799
MAPE: 0.04983746947600494

In [115]:
### The random forest regressor performed the best, getting the lowest error rates across all metrics, with a 31.779 RMSE, a 11.029 MAE, and a 0.050 MAPE.